version: '3.9'

name: authentication-service

services:
  api:
    container_name: 'api'
    build:
      context: './src/API'
      dockerfile: 'Dockerfile'
    ports:
      - '5050:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - default
      - infrastructure

networks:
  default:
    name: authentication-service
  infrastructure:
    external: true